CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255),
    nickname VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(500),
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE oauth_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_oauth_accounts_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_oauth_accounts_provider_user UNIQUE (provider, provider_user_id)
);

CREATE TABLE regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sido VARCHAR(50) NOT NULL,
    sigungu VARCHAR(80) NOT NULL,
    eupmyeondong VARCHAR(80) NOT NULL,
    legal_dong_code VARCHAR(10) NOT NULL,
    center_latitude NUMERIC(10, 7),
    center_longitude NUMERIC(10, 7),
    CONSTRAINT uk_regions_legal_dong_code UNIQUE (legal_dong_code)
);

CREATE TABLE room_handover_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    title VARCHAR(120) NOT NULL,
    deposit BIGINT NOT NULL,
    monthly_rent BIGINT NOT NULL,
    maintenance_fee BIGINT,
    available_from DATE,
    contract_until DATE,
    nearest_station VARCHAR(80),
    room_type VARCHAR(30) NOT NULL,
    floor VARCHAR(30),
    pet_allowed BOOLEAN,
    landlord_consent_status VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_room_handover_posts_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_room_handover_posts_region FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE TABLE community_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    category VARCHAR(30) NOT NULL,
    title VARCHAR(120) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_community_posts_author FOREIGN KEY (author_id) REFERENCES users (id),
    CONSTRAINT fk_community_posts_region FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id BIGINT NOT NULL,
    post_type VARCHAR(30) NOT NULL,
    post_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_comments_author FOREIGN KEY (author_id) REFERENCES users (id)
);

CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL,
    target_type VARCHAR(40) NOT NULL,
    target_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_reports_reporter FOREIGN KEY (reporter_id) REFERENCES users (id)
);

CREATE TABLE public_data_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id BIGINT,
    source VARCHAR(80) NOT NULL,
    data_type VARCHAR(80) NOT NULL,
    payload_json TEXT NOT NULL,
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_public_data_snapshots_region FOREIGN KEY (region_id) REFERENCES regions (id)
);

CREATE TABLE event_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    event_name VARCHAR(80) NOT NULL,
    properties_json TEXT,
    request_id VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_event_logs_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_oauth_accounts_user_id ON oauth_accounts (user_id);
CREATE INDEX idx_room_handover_posts_region_status ON room_handover_posts (region_id, status);
CREATE INDEX idx_room_handover_posts_author_id ON room_handover_posts (author_id);
CREATE INDEX idx_community_posts_region_category ON community_posts (region_id, category);
CREATE INDEX idx_comments_post ON comments (post_type, post_id);
CREATE INDEX idx_reports_target ON reports (target_type, target_id);
CREATE INDEX idx_public_data_snapshots_region_type ON public_data_snapshots (region_id, data_type);
CREATE INDEX idx_event_logs_event_created ON event_logs (event_name, created_at);
